### PR TITLE
fix: improper list construction

### PR DESCRIPTION
**Pull request by mad42**

### CODE REVIEW

**Comment by mad42** [comment]
@maennchen 👋

**Comment by maennchen** [comment]
@mad42 Sorry, I somehow missed this PR.

I don't see how an improper list is a problem since an iolist may actually be an improper list.

`maybe_improper_list(byte() | binary() | iolist(), binary() | []) | binary()` should be the expected type of an iolist.

Did you experience any issues? If yes, which ones?

**Comment by mad42** [comment]
I have many ElixirLS Dialyzer error saying:
```
List construction (cons) will produce an improper list, because its second argument is <<_::136>>.
```

**Comment by maennchen** [comment]
@mad42 This is the one place i know where the improper list actually makes a lot of sense. I'd rather not introduce an extra list.

I think that we should just disable that warning instead in this case. http://erlang.org/doc/man/dialyzer.html#requesting-or-suppressing-warnings-in-source-files

**Comment by maennchen** [comment]
Thanks @mad42

**Pull request merged**
